#!/usr/bin/env python
from __future__ import print_function

import logging
import logging.config
import os
import os
from argparse import ArgumentParser
from collections import namedtuple
from copy import deepcopy
from pprint import pprint, pformat

import yaml
from colorlog import ColoredFormatter
from tqdm import tqdm


class TqdmHandler(logging.StreamHandler):
    def __init__(self):
        logging.StreamHandler.__init__(self)

    def emit(self, record):
        msg = self.format(record)
        tqdm.write(msg)


logging.config.dictConfig({
    'version': 1,
    'disable_existing_loggers': False,
    'loggers': {
        'vcstool.executor': {
            'level': 'INFO',
        }
    },
    'root': {
        'level': 'INFO',
    },
})

formatter = ColoredFormatter("%(log_color)s[%(levelname).4s] %(message)s")
console = TqdmHandler()
console.setFormatter(formatter)
logging.getLogger().addHandler(console)

logger = logging.getLogger(__name__)


class Target(object):
    def __init__(self, key):
        self.key = key

    def __repr__(self):
        return "%s(%s)" % (self.__class__.__name__, pformat(self.__dict__))


class MetaPackage(Target):
    def __init__(self, key, dependencies):
        super(MetaPackage, self).__init__(key)
        self.dependencies = dependencies


class Package(Target):
    def __init__(self, key, type, url, version, subdir):
        super(Package, self).__init__(key)
        self.type = type
        self.url = url
        self.version = version
        self.subdir = subdir


class ROSSystem(Target):
    def __init__(self, key, name):
        super(ROSSystem, self).__init__(key)
        self.name = name


class System(Target):
    def __init__(self, key, name):
        super(System, self).__init__(key)
        self.name = name


class Pip(Target):
    def __init__(self, key, name):
        super(Pip, self).__init__(key)
        self.name = name


class Redirect(Target):
    def __init__(self, key, name):
        super(Redirect, self).__init__(key)
        self.name = name


def parse_target(path):
    basename = os.path.basename(path)
    logger.debug("parsing '%s'", basename)

    ret = None
    try:
        with open(os.path.join(path, 'install.yaml')) as f:
            target = yaml.load(f)
            ret = parse_target_yaml(basename, target)
    except IOError:
        pass
    try:
        with open(os.path.join(path, 'install.bash')) as f:
            if ret:
                logger.warn("also install.bash found for '%s'", basename)
            else:
                ret = parse_target_bash(f.read())
    except IOError:
        if ret:
            pass
        else:
            logger.debug('install.bash not found')

    if ret:
        return ret
    logger.warn("no target found for '%s'", basename)
    return None


def parse_target_bash(f):
    lines = f.splitlines()
    if len(lines) == 1:
        logger.warn('unknown setup.bash')
    else:
        logger.info("complex install.bash found")
    return None


def parse_target_yaml(key, target):
    if len(target) == 1:
        return parse_single_target(key, target[0])
    else:
        return parse_meta_target(key, target)


def parse_meta_target(key, targets):
    deps = []
    for target in targets:
        dep = parse_single_target(key, target)
        if isinstance(dep, Redirect):
            name = dep.name
            if name.startswith('ros-'):
                name = name[4:]
            deps.append(name)
        elif isinstance(dep, System):
            deps.append(dep.name)
        elif isinstance(dep, ROSSystem):
            deps.append(dep.name)
        else:
            logger.error("unexpected target found in metatarget '%s', skipping", target)
            return None
    return MetaPackage(key, deps)


def parse_single_target(key, target):
    target = target.copy()
    tt = target.pop('type')

    if tt == 'ros':
        return parse_ros_target(key, **target)
    elif tt == 'system':
        return parse_system_target(key, **target)
    elif tt == 'target':
        return parse_redirect_target(key, **target)
    elif tt == 'ros-rosbuild':
        logger.error('rosbuild target')
    elif tt == 'pip':
        return parse_pip_target(key, **target)
    else:
        logger.error('unknown target type: %s' % tt)


def parse_ros_target(key, source, **kwargs):
    assert not kwargs, "Unexpected kwargs: %s" % kwargs

    source = source.copy()
    tt = source.pop('type')

    if tt == 'git':
        # remove dash in sub-dir
        if 'sub-dir' in source:
            source['subdir'] = source.pop('sub-dir')
        return parse_source(key, tt, **source)
    elif tt == 'system':
        return parse_ros_system(key, **source)
    else:
        assert False, tt


def parse_system_target(key, name, **kwargs):
    assert not kwargs, "Unexpected kwargs: %s" % kwargs

    return System(key, name)


def parse_redirect_target(key, name, **kwargs):
    assert not kwargs, "Unexpected kwargs: %s" % kwargs

    return Redirect(key, name)


def parse_pip_target(key, name, **kwargs):
    assert not kwargs, "Unexpected kwargs: %s" % kwargs

    return Pip(key, name)


def parse_source(key, type, url, version='master', subdir=None, **kwargs):
    assert not kwargs, "Unexpected kwargs: %s" % kwargs

    return Package(key, type, url, version, subdir)


def parse_ros_system(key, name, **kwargs):
    assert not kwargs, "Unexpected kwargs: %s" % kwargs

    return ROSSystem(key, name)


if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('-v', '--verbose', action='store_true')
    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    data_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'tue-env')
    target_path = os.path.join(data_path, 'installer', 'targets')

    targets = (os.path.join(target_path, o) for o in os.listdir(target_path))
    targets = [t for t in targets if os.path.isdir(t)]

    mps = {}
    rosdeps = []
    pkgs = {}
    for target in tqdm(targets):
        t = parse_target(target)
        if isinstance(t, MetaPackage):
            mps[t.key] = t
        elif isinstance(t, Package):
            url = t.url
            if url.endswith('.git'):
                url = url[:-4]
            _, _, last = url.rpartition('/')
            if last in pkgs:
                pkgs[last].append(t)
            else:
                pkgs[last] = [t]
        elif isinstance(t, System):
            rosdeps.append(t)
        elif isinstance(t, ROSSystem):
            rosdeps.append(t)
        elif isinstance(t, Pip):
            rosdeps.append(t)
        elif isinstance(t, Redirect):
            logger.warn("'%s'", t)
        elif t is None:
            pass
        else:
            assert False, t

    # first output meta packages
    mps_path = os.path.join(os.path.dirname(__file__), '..', 'tue_metapackages')
    mps_output = {}
    for name, mp in mps.items():
        name = name.replace('-', '_')
        deps = [d.replace('-', '_') for d in mp.dependencies]
        mps_output[name] = deps

    with open(os.path.join(mps_path, 'deps.yaml'), 'w') as f:
        yaml.dump(mps_output, f, default_flow_style=False)

    # then output packages
    pkgs_output = {}
    for repo, pkgs in pkgs.items():
        source = {}
        for pkg in pkgs:
            if not pkg.subdir:
                assert pkg.key[4:] == repo
            s = {
                'type': pkg.type,
                'url': pkg.url,
                'version': pkg.version,
            }
            if source:
                assert source == s
            else:
                source = s
        source['packages'] = [pkg.key[4:] for pkg in pkgs]
        pkgs_output[repo] = {
            'source': source,
        }

    pkgs_output['tue_metapackages'] = {
        'source': {
            'packages': mps_output.keys(),
            'type': 'git',
            'url': 'https://github.com/Rayman/rosdistro',
            'version': 'master',
        }
    }

    with open(os.path.join(os.path.dirname(__file__), '..', 'data', 'distro.template')) as f:
        template = f.read()

    d = yaml.dump({'repositories': pkgs_output}, default_flow_style=False)
    distro = template.format(repositories=d)

    distro_path = os.path.join(os.path.dirname(__file__), '..', 'kinetic')
    with open(os.path.join(distro_path, 'distribution.yaml'), 'w') as f:
        f.write(distro)

    print('OK')
